# Generated by Django 5.1.3 on 2024-11-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(max_length=100, unique=True)),
                ('variations', models.JSONField(help_text='List of possible column names for this field type')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['field_type'], name='comparer_fi_field_t_029af2_idx')],
            },
        ),
    ]
