# Generated by Django 5.1.3 on 2024-11-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0006_alter_userstats_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonhistory',
            name='execution_time',
            field=models.FloatField(blank=True, help_text='Execution time in seconds', null=True),
        ),
    ]
